stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  REGISTRY: "ghcr.io"
  REGISTRY_IMAGE: "ghcr.io/vektor-code/ingestor-backend"
  PROD_TAG: "prod-$CI_COMMIT_SHORT_SHA"
  PROD_LATEST: "prod-latest"

build-and-push:
  stage: build
  image: docker:24.0.9
  services:
    - name: docker:24.0.9-dind
      alias: docker
  only:
    - prod
  script:
    - |
      if [ -n "$REGISTRY_USER" ] && [ -n "$REGISTRY_PASSWORD" ]; then
        echo "$REGISTRY_PASSWORD" | docker login $REGISTRY -u "$REGISTRY_USER" --password-stdin
      elif [ -n "$CI_REGISTRY_USER" ] && [ -n "$CI_REGISTRY_PASSWORD" ]; then
        docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
      fi
    - docker build -t $REGISTRY_IMAGE:$PROD_TAG -t $REGISTRY_IMAGE:$PROD_LATEST .
    - docker push $REGISTRY_IMAGE:$PROD_TAG
    - docker push $REGISTRY_IMAGE:$PROD_LATEST
